### ISSUE TITLE
No android.permission.INTERACT_ACROSS_USERS

### ISSUE THREAD

**Issue by migo1271** [IngoZenz/personaldnsfilter#17]
On my Tablet with Android 8.1.0 dnsfilter throws following message and does not work:

Initializing ...
***Initializing PersonalDNSFilter Version 1.50.29!***
Running on SDK27
Using Blocking Mode!
java.lang.SecurityException: getPackageUid: Neither user 10285 nor current process has android.permission.INTERACT_ACROSS_USERS.
at android.os.Parcel.readException(Parcel.java:2029)
at android.os.Parcel.readException(Parcel.java:1975)
at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:2459)
at android.net.VpnService$Builder.establish(VpnService.java:1026)
at dnsfilter.android.DNSFilterService.onStartCommand(DNSFilterService.java:288)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3693)
at android.app.ActivityThread.-wrap22(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1827)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:7000)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

Seems. there is a permission missing for multi user environments?

Many thanks.

**Comment by IngoZenz** [comment]
Guess you need to grant the current user the authorization to start / configure a VPN ?

**Comment by IngoZenz** [comment]
This can not be fixed in the app.
Seems on this device you can only run the app with the user who has installed it.

**Comment by migo1271** [comment]
Ok, my device is a Samsung Galaxy Tab A6 with Android 8.1. Both, main user who installed the app, and the limited user get this error message. I will have a deeper look into the user's configuration.
Many thanks.

**Comment by IngoZenz** [comment]
Thanks - please let me know the result.
I researched a bit in the web searching for "android vpn INTERACT_ACROSS_USERS".
It could be a firmware issue on your device.

**Comment by migo1271** [comment]
I deleted the additional user. Now it works as expected.

**Comment by IngoZenz** [comment]
Thanks for the update!
