### ISSUE TITLE
VPN fails to start in work profile

### ISSUE THREAD

**Issue by ogamibird** [IngoZenz/personaldnsfilter#185]
The app does not seem to work in a work profile environment because it seems to look in the wrong file paths. The correct file path in the work profile would be in my case 
/storage/emulated/11/Android/data/dnsfilter.android/files
Phone is Samsung S9+ with Android 10
Storage permission  is granted

Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/dnsfilter.android/files/PersonalDNSFilter/dnsfilter.conf: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.(FileInputStream.java:159)
	at dnsfilter.DNSFilterManager.readConfig(DNSFilterManager.java:272)
	... 17 more
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8044)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 19 more

**Comment by IngoZenz** [comment]
Thanks for letting me know. I am using the external storage dir folder returned by the API. https://developer.android.com/reference/android/content/Context#getExternalFilesDir(java.lang.String).
It is getting more and more tricky recently with Android's file permission management...
