### ISSUE TITLE
Crash / doesn't start when ipv6 is disabled

### ISSUE THREAD

**Issue by elclaudio** [IngoZenz/personaldnsfilter#56]
When ipv6 is disabled on Android with 
`sysctl net.ipv6.conf.all.disable_ipv6=1`

dnsfilter won't start or restart. In the log window, there are messages like

`java.lang.IllegalStateException: Cannot set address`

Could you fix it please ?
And thanks you very much for this great piece of software, coupled with afwall+ it's even greater !

**Comment by IngoZenz** [comment]
Could you please provide the full stack trace?

**Comment by elclaudio** [comment]
Hi thanks you for your quick response

I installed the version you provided, but unfortunately, it doesn't solve the issue.

here is the full message showed in the log window :

```
****This is personalDNSfilter V+1503405-dev01****

Initializing ...
***Initializing PersonalDNSFilter Version 1503405-dev01!***
Using Directory: /storage/57f8f4bc-abf4-655f-bf67-946fc0f9f25b/PersonalDNSFilter/
Aquired WIFI lock and partial wake lock!
Released WIFI lock and partial wake lock!
Using Blocking Mode!
java.lang.IllegalStateException: Cannot set address
	at android.os.Parcel.createException(Parcel.java:1958)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1976)
	at android.net.VpnService$Builder.establish(VpnService.java:806)
	at dnsfilter.android.DNSFilterService.initVPN(DNSFilterService.java:390)
	at dnsfilter.android.DNSFilterService.onStartCommand(DNSFilterService.java:443)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3705)
	at android.app.ActivityThread.access$1600(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.connectivity.Vpn.jniSetAddresses(Native Method)
	at com.android.server.connectivity.Vpn.establish(Vpn.java:1076)
	at com.android.server.ConnectivityService.establishVpn(ConnectivityService.java:3710)
	at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java
```

As a side note I would like to ask you something : do you know how to use personalDNSfilter when tethering via either usb or wifi ? I use tethering a lot and I wish that all dns request from the connected device could pass through dnsfilter (filtering dns + use others dns) because my isp force their own dns whatever you choose, except when using DoT or DoH.

**Comment by IngoZenz** [comment]
Regarding your other question? In case you device is rooted you might run pDNSf also in DNS proxy mode and set your phone as DNS server. Might be an option...

**Comment by elclaudio** [comment]
oh thanks a lot.. I wasn't aware that pDNSf could run as a dns proxy, how to do this, I haven't found any setting regarding this in the gui ?

**Comment by IngoZenz** [comment]
It is not on the GUI.
Check the dnsfilter.conf file in the petsonaldnsfilter folder. There is a setting like dnsProxyOnAndroid...

**Comment by elclaudio** [comment]
I've originaly downloaded the apk on f-droid so, I didn't know there was another "full package" with doc etc thanks you very much, will read it asap.

**Comment by IngoZenz** [comment]
welcome! Proxy mode is also supported by the android version on rooted devices...
Regarding the issue - could you  please test again the attached version?

[dnsfilter-1503405-dev02.zip](https://github.com/IngoZenz/personaldnsfilter/files/3972423/dnsfilter-1503405-dev02.zip)

**Comment by elclaudio** [comment]
Hi IngoZenz
the dev02 version is better, it appear to work when the phone is connected to cellular but the app still crash when connected to wifi access point, more precisely when clicking the restart button.

when connected to cellular I see :
IPV4 supported:/127.0.0.1 (I only see this line, no mention of IPv6 supported) if I click restart, it doesnt crash

when I connect to wifi I see 2 lines: 
IPV4 supported:/127.0.0.1
IPV6 supported:/fe80::XXXX:XXXX:XXXX:XXXX%wlan0
if I click restart, it crash

```
java.lang.IllegalStateException: Cannot set address
	at android.os.Parcel.createException(Parcel.java:1958)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1976)
	at android.net.VpnService$Builder.establish(VpnService.java:806)
	at dnsfilter.android.DNSFilterService.initVPN(DNSFilterService.java:405)
	at dnsfilter.android.DNSFilterService.onStartCommand(DNSFilterService.java:458)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3705)
	at android.app.ActivityThread.access$1600(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.connectivity.Vpn.jniSetAddresses(Native Method)
	at com.android.server.connectivity.Vpn.establish(Vpn.java:1076)
	at com.android.server.ConnectivityService.establishVpn(ConnectivityService.java:3710)
	at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:577)
	at android.os.Binder.execTransact(Binder.java:731)
```

**Comment by IngoZenz** [comment]
Ok..so seems it's getting tricky....in this case I think the best will be to have a configuration setting to disable ipv6 when needed. Will see...

**Comment by elclaudio** [comment]
no problems, thanks you for your time, I just block all ipv6 for now

**Comment by IngoZenz** [comment]
Shoild be fixed with https://github.com/IngoZenz/personaldnsfilter/commit/782ed8b4506e0cc40d688b73f9520c252c7f01f5

In order to diables IPV6, you need to set dnsfilter.conf setting:
```
# IP Version Support
ipVersionSupport =4
```

[dnsfilter-1503405-dev04.zip](https://github.com/IngoZenz/personaldnsfilter/files/3987169/dnsfilter-1503405-dev04.zip)

**Comment by elclaudio** [comment]
Thanks you, it works now, no more crash when ipv6 is disabled !

**Comment by IngoZenz** [comment]
Fix is released with https://github.com/IngoZenz/personaldnsfilter/releases/tag/1.50.35.0
