### ISSUE TITLE
[Android 10] App no longer work in work profile and cause device crash + bootloop

### ISSUE THREAD

**Issue by kowith337** [IngoZenz/personaldnsfilter#68]
I've run DNSFilter app parallel both main and work profile because each profile are use separate connections, use VPN app in main profile doesn't mean to apply in work profile too, so I need to run both.

It's work well in Android 9, even have some error in app log, but today I just received Android 10 update and try out...

After update system, I got bootloop-like experience, so I just reboot in safe mode then reboot to normal mode.

Luckily, I didn't set pDNSF in work profile as Always-on VPN, I will unable to use my device if I've previously set to that.

So I will reconfigure the app from `dnsfilter.conf` to disabled autostart and try to run app in work profile again, but it constant crash and reboot my device.

### Device info
**Model**: XT1970-3 (Motorola one vision)
**Codename**: `kane_sprout`
**Android Version**: 10 (January 2020 patch)

### Logcat (Logged range between WARN and FATAL)
```java
02-06 18:10:32.802 19121 19121 E AndroidRuntime: FATAL EXCEPTION: main
02-06 18:10:32.802 19121 19121 E AndroidRuntime: Process: dnsfilter.android, PID: 19121
02-06 18:10:32.802 19121 19121 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
02-06 18:25:58.469 19454 19454 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
02-06 18:25:58.469 19454 19454 E AndroidRuntime: java.lang.SecurityException: UID 1010473 does not have permission to content://media/external/audio/media/285638 [user 0]
02-06 18:25:58.469 19454 19454 E AndroidRuntime: 	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermission(UriGrantsManagerService.java:1179)
02-06 18:25:58.469 19454 19454 E AndroidRuntime: 	at com.android.server.uri.UriGrantsManagerService.grantUriPermission(UriGrantsManagerService.java:767)
02-06 18:25:58.469 19454 19454 E AndroidRuntime: 	at com.android.server.uri.UriGrantsManagerService.grantUriPermissionFromOwner(UriGrantsManagerService.java:208)
02-06 18:25:58.469 19454 19454 E AndroidRuntime: 	at com.android.server.notification.NotificationManagerService.grantUriPermission(NotificationManagerService.java:6684)
02-06 18:25:58.469 19454 19454 E AndroidRuntime: 	at com.android.server.notification.NotificationManagerService.updateUriPermissions(NotificationManagerService.java:6656)
02-06 18:25:58.469 19454 19454 E AndroidRuntime: 	at com.android.server.notification.NotificationManagerService$NotificationListeners.notifyPostedLocked(NotificationManagerService.java:8019)
02-06 18:25:58.469 19454 19454 E AndroidRuntime: 	at com.android.server.notification.NotificationManagerService$NotificationListeners.notifyPostedLocked(NotificationManagerService.java:7965)
02-06 18:25:58.469 19454 19454 E AndroidRuntime: 	at com.android.server.notification.NotificationManagerService$PostNotificationRunnable.run(NotificationManagerService.java:5475)
02-06 18:25:58.469 19454 19454 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
02-06 18:25:58.469 19454 19454 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-06 18:25:58.469 19454 19454 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
02-06 18:25:58.469 19454 19454 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:582)
02-06 18:25:58.469 19454 19454 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:378)
02-06 18:25:58.469 19454 19454 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-06 18:25:58.469 19454 19454 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
02-06 18:25:58.469 19454 19454 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:919)
02-06 18:25:58.628 20123 21285 E AndroidRuntime: FATAL EXCEPTION: highpool[1]
02-06 18:25:58.628 20123 21285 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 20123
02-06 18:25:58.628 20123 21285 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
02-06 18:25:58.629   820   820 E AndroidRuntime: FATAL EXCEPTION: main
02-06 18:25:58.629   820   820 E AndroidRuntime: Process: dnsfilter.android, PID: 820
02-06 18:25:58.629   820   820 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
02-06 18:25:58.630 20123 21356 E AndroidRuntime: FATAL EXCEPTION: highpool[3]
02-06 18:25:58.630 20123 21356 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 20123
02-06 18:25:58.630 20123 21356 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
02-06 18:25:58.706   730   730 E AndroidRuntime: FATAL EXCEPTION: main
02-06 18:25:58.706   730   730 E AndroidRuntime: Process: com.google.android.apps.messaging, PID: 730
02-06 18:25:58.706   730   730 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
02-06 18:25:58.971   344   409 E AndroidRuntime: FATAL EXCEPTION: CronetInit
02-06 18:25:58.971   344   409 E AndroidRuntime: Process: com.google.android.gms, PID: 344
02-06 18:25:58.971   344   409 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
02-06 18:25:58.998 29438 29438 E AndroidRuntime: FATAL EXCEPTION: main
02-06 18:25:58.998 29438 29438 E AndroidRuntime: Process: com.google.android.inputmethod.latin, PID: 29438
02-06 18:25:58.998 29438 29438 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
02-06 18:25:59.145 19316   944 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe719c10c in tid 944 (HwBinder:19316_), pid 19316 (audio@2.0-servi)
```

**Comment by IngoZenz** [comment]
looks liek Android bug- No dnsfilter code involved here...

**Comment by kowith337** [comment]
Forgot to add how to reproduce
1. Setup work profile by Shelter
2. Clone pDNSF from main profile or install APK in shelter
3. Try to run app

But my setup is different because I've setup Shelter before upgrade to Android 10.

Still no luck to run without crash and reboot, even `DisableDNS = true`
> Although I didn't root but just set that preference to test if pDNSF can run even didn't run as VPN.

It seems like the app fail to run and still don't know what things that cause the device crash, even I've remove app config folder, it can be run and show full UI, but it's still crash after I've allow the app to create VPN once confirmation dialog show.

**Comment by IngoZenz** [comment]
I have no idea! I fear I can do nothing to fix this.
